# Generated by Django 5.0.2 on 2024-03-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='type',
        ),
    ]
