# Generated by Django 5.0.2 on 2024-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_remove_thing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='doneOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
